### ISSUE TITLE
Out of sync received. Routing

### ISSUE THREAD

**Issue by dnister** [Remotes/Remotes#2]
Try check posibility of remote control but recive next text in console of browser with presentation( this text from console when loaded http://remotes.io/) 

```
[APP] resolved widget registration widget.prod.js:5462
event.returnValue is deprecated. Please use the standard event.preventDefault() instead.
pusher initiailized OK widget.prod.js:5161
enumerating members 
c {_members_map: Object, count: 2, me: Object, each: function, get: function}
 widget.prod.js:5184
enumerating members 
c {_members_map: Object, count: 2, me: Object, each: function, get: function}
 widget.prod.js:5184
Out of sync received. Routing ... widget.prod.js:3084
[APP] subscribers changed 
[Object]
0: Object
length: 1
__proto__: Array[0]
 widget.prod.js:5476
[LOCAL RECEIVER] got data Object {destination: "oats", signal: "oats.client.out_of_sync", t_dispatch_rcvd: 1394550594004}

```

**Comment by Timothee** [comment]
I'm not sure of the problem you're having. I just tested remotes.io and though I do see this message in the console, it seems to be working fine. Can you elaborate?

**Comment by dnister** [comment]
Sure, look plese in attached screenshot
![remotes](https://f.cloud.github.com/assets/1484714/2399589/38d4513a-aa00-11e3-95d9-6de7a06f2294.png)

**Comment by Timothee** [comment]
I see that too but what is the actual issue? Is the remote not working for you?

**Comment by dnister** [comment]
Yes, the remote isn't working for me

**Comment by callmephilip** [comment]
What device and browser are you using?

**Comment by dnister** [comment]
Device: prestigio multiphone 4055 duo
Browser: any of new, on screenshot for example Google Chrome 33.0.1750.149

**Comment by callmephilip** [comment]
So i assume, on the phone, you are using a standard Android WebView within some sort of QR code scanner. Is this correct? any chance to know the specs of the WebView. I suspect this might be the source of problems

**Comment by dnister** [comment]
I use browser Google Chrome on my Android device if this can help you. All other is standart for this mobile device. But I receive error message after few secons when browser on pc loaded, no mobile device is used on this step.

**Comment by Timothee** [comment]
Is the issue you're reporting just about the "Out of sync" message that shows up in the console? Or have you used a QR code scanner and then it doesn't work?

From your last comment, it seems that at this point you haven't used your phone at all yet? If that's a case, this is not an issue. The page outputs messages to the console but that doesn't mean it's not working. Before you connect your phone, the page is in fact out of sync since it's not synced to any devices.

If you scan the QR code and it doesn't seem to connect, then there is an issue indeed.

**Comment by dnister** [comment]
I tryed again and now all work. May be problem was with slow internet connection, because now when I scan background on remotes.io changed and I can swipe from my device.

I think ticket can be closed.

Thx
