### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by rskuipers** [Remotes/Remotes#3]
I've been getting an internal server error for the past few days

```
POST http://www.remotes.io/extension/register/ 500 (Internal Server Error)
```

I'm using your plugin together with RevealJS and it worked fine for me before.
I really enjoy using your service, I hope you can get this fixed :)

```
Request URL: http://www.remotes.io/extension/register/
Request Method: POST
Status Code: 500 Internal Server Error

Request Headers
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8,nl;q=0.6
Connection: keep-alive
Content-Length: 26
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Host: www.remotes.io
Origin: http://www.remotes.io
Referer: http://www.remotes.io/widgets/sync/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/33.0.1750.152 Chrome/33.0.1750.152 Safari/537.36
X-Requested-With: XMLHttpRequest

Form Data
application_key: 1234567890
Response Headers
Connection: keep-alive
Content-Length: 134
Content-Type: text/html 
```

**Comment by callmephilip** [comment]
thanks for reporting this. i think we hit a storage limit on the database instance. will try to get it fixed asap

**Comment by rskuipers** [comment]
@callmephilip I hate to ask this but, any chance this can be fixed today? I have a presentation today and I'd love to use this library. If there's anything I can do to help let me know.

**Comment by bduff9** [comment]
I also would love this to be fixed in the next week as I have a very large presentation on JS that would be great to show off reveal.js and remotes.js.  Thanks!

**Comment by callmephilip** [comment]
Hello guys. Massive apologies for the epic delay on this one. Finally managed to get my hands on it and fixed our production database so Remotes are back up and running.

**Comment by xescugc** [comment]
I think it's happening again, is it possible?

**Comment by kaosbeat** [comment]
yep, server error 500 :/
this only hapens on presentation day :)

Kasper

**Comment by callmephilip** [comment]
Sorry for the ridiculous delay on this. Should be fixed now
