### ISSUE TITLE
 (BAD REQUEST) 

### ISSUE THREAD

**Issue by octosteve** [Remotes/Remotes#4]
Demo site is throwing an error in the console.

POST http://www.remotes.io/auth/channel/resolve/ 400 (BAD REQUEST) 

when the qr code comes up.

**Comment by callmephilip** [comment]
Which site are you referring to, Steven?

**Comment by octosteve** [comment]
Thanks for getting back to me! It's the demo site remotes.io . I noticed it's not happening in Incognito mode so I'm hunting for a broken plugin. Thanks again.
